### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by lanzone1** [skynettechnologies/all-in-one-accessibility-google-tag-manager#1]
When reviewing your template we've noticed that it is using user-defined parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by skynetindia** [comment]
@lanzone1 

We updated the template using [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) parameters. 

Please check and give us feedback.

**Comment by lanzone1** [comment]
Looks good, thanks. You template should be approved shortly.
